### PR TITLE
JavaScript IR Support

### LINKED ISSUE #60: Support JavaScript IR Compiler

### PR DESCRIPTION
**Pull request by KVelasco**
Resolves #60

### CODE REVIEW

**Comment by KVelasco** [comment]
Functions that uses Kotlin DataTime library need to be annotated with `@ExperimentalTime` as not doing so was resulting in a build error. 

> This declaration is experimental and its usage must be marked with '@kotlin.time.ExperimentalTime' or '@OptIn(kotlin.time.ExperimentalTime::class)'

**Comment by KVelasco** [comment]
@twyatt do we need PR #65 to be merged before merging this PR?

**Comment by twyatt** [comment]
> @twyatt do we need PR #65 to be merged before merging this PR?
> 
> Getting the following build error
> 
> > Execution failed for task ':coroutines:signAndroidDebugPublication'.
> > The key ID must be in a valid form (eg 00B5050F or 0x00B5050F), given value:

I _think_ it will fix your build issues. I'll get it ready and pull it out of draft.

**Review by cedrickcooke — APPROVED** [review]

**Comment by twyatt** [comment]
@KVelasco just a heads up, did an `Update branch` on this PR as I wanted to get it in a compiling state to test with some other things on my local machine. Appologies.

**Comment by twyatt** [comment]
Please disable `binary-compatibility-validator` for now:

```kotlin
    // Breaks with:
    // A problem occurred configuring project ':registration'.
    // > org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'apiBuild' as a task with that name already exists.
    //
    // Disabling until https://github.com/Kotlin/binary-compatibility-validator/issues/38 is fixed.
//    id("binary-compatibility-validator") version "0.6.0"
```

**Review by twyatt — CHANGES_REQUESTED** [review]
Please disable `binary-compatibility-validator` for now:

```kotlin
    // Breaks with:
    // A problem occurred configuring project ':registration'.
    // > org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'apiBuild' as a task with that name already exists.
    //
    // Disabling until https://github.com/Kotlin/binary-compatibility-validator/issues/38 is fixed.
//    id("binary-compatibility-validator") version "0.6.0"
```

**Review by twyatt — APPROVED** [review]

**Pull request merged**
