### PR TITLE
Add support for Apple Silicon

### PR DESCRIPTION
**Pull request by lammertw**
This is a requirement to build Kable for Apple Silicon: https://github.com/JuulLabs/kable/pull/209

### CODE REVIEW

**Review by cedrickcooke — APPROVED** [review]
Looks great to me. CC @twyatt just for the tie to Kable.

**Review by twyatt — APPROVED** [review]
Tested that explicitly using node 16 works with both [SensorTag sample](https://github.com/JuulLabs/sensortag) and internal projects.

**Comment by twyatt** [comment]
Thanks for the contribution @lammertw!

**Comment by lammertw** [comment]
You're very welcome

**Pull request merged**
