### PR TITLE
Add 'encoding' module with BitSet support

### PR DESCRIPTION
**Pull request by twyatt**

### CODE REVIEW

**Review by cedrickcooke — APPROVED** [review]
Wow 10/10 such beautiful code 😉

**Comment by twyatt** [comment]
> Wow 10/10 such beautiful code 😉

Haha, well played my friend. 😝

**Review by sdonn3 — APPROVED** [review]

**Comment by sdonn3** [comment]
> Wow 10/10 such beautiful code 😉

sigh

**Review by QuantumRand — COMMENTED** [review]
Maybe I'm misunderstanding the intention behind `BitSet`, but why is the sign bit at the end?

**Comment by twyatt** [comment]
Not quite what I was going for, but I guess @cedrickcooke your name is on it (even if you have to dig for it).

Screen Shot 2021-03-15 at 2 24 48 PM

**Comment by twyatt** [comment]
> Maybe I'm misunderstanding the intention behind `BitSet`, but why is the sign bit at the end?

Does its usage help clear up any misunderstandings? https://github.com/JuulLabs/chai/pull/48

**Comment by QuantumRand** [comment]
> > Maybe I'm misunderstanding the intention behind `BitSet`, but why is the sign bit at the end?
> 
> @QuantumRand Does its usage help clear up any misunderstandings? [JuulLabs/chai#48](https://github.com/JuulLabs/chai/pull/48)

@twyatt I understand how it can be used. But I'm confused about the tests
```
var set = Int.MIN_VALUE.bits
        for (i in 0..30) assertFalse(set[i])
        assertTrue(set[31])
```
How is the Endianness enforced?

**Comment by twyatt** [comment]
> @twyatt I understand how it can be used. But I'm confused about the tests
> 
> ```
> var set = Int.MIN_VALUE.bits
>         for (i in 0..30) assertFalse(set[i])
>         assertTrue(set[31])
> ```
> 
> How is the Endianness enforced?

I see your point. Looking at the different platforms we support:

| Platform | Endianness |
|-|-|
| JVM | Big |
| JavaScript | [Platform dependent (usually Little)](https://stackoverflow.com/a/7870190) |
| MacOS | [Platform dependent](https://developer.apple.com/documentation/corefoundation/byte-order_utilities) |

They don't seem to be consistent at all, yet the tests are passing on all platforms. 🤯 

I'll look into it further. Unless @cedrickcooke understands what magic (or common misunderstanding) is going on here?

**Comment by cedrickcooke** [comment]
@twyatt @QuantumRand

The magic here is that endianess doesn't matter for any of the code I've written. In every language I know of, even stuff like C, bit 0 is always the least significant bit, and the higher bits are always more significant. Operations like bitshifts are actually defined in terms of bit indices, so they're endian-independent for free.

In general, the only time you have to deal with endian-ness is if you're taking like, a stream of bytes, and re-assembling into larger integers. Even then, what you'll find is device drivers will handle endianess of the individual bits in a byte, so all you have to know is whether to do `bytes[3] << 24 & bytes[2] << 16 & bytes[1] << 8 & bytes[0]` or `bytes[0] << 24 & bytes[1] << 16 & bytes[2] << 8 & bytes[3]`

**Comment by twyatt** [comment]
Ohh. So **byte** order matters whereas **bit** order does not. 💯

**Comment by cedrickcooke** [comment]
Yeah! And by the time you're dealing with `int`/`long`/etc, that's already handled.

**Comment by cedrickcooke** [comment]
As an aside, the test _is_ still dependent on the hardware semantics of integers. But if we're ever dealing with a platform that doesn't use two's complement I'll eat my hat.

**Comment by cedrickcooke** [comment]
Another bit of trivia: modern CPUs often have bi-endian IO instructions, so you can directly read full 32/64 bit integers from both big and little endian sources without even needing to do that bitshift stuff I mentioned above. AFAIK, this is mostly used to help optimize network IO, since most of those protocols are big-endian but most modern hardware is little endian.

**Pull request merged**
