### PR TITLE
Add iOS targets to `test` module and bump dependencies

### PR DESCRIPTION
**Pull request by twyatt**
- Change `jcenter` to `mavenCentral`
- Upgrade dependencies (sans `binary-compatibility-validator` — blocked by https://github.com/Kotlin/binary-compatibility-validator/issues/38)
  - Bump JaCoCo version due to https://youtrack.jetbrains.com/issue/KT-44757
- Enable hierarchical project structure
- Add `iosArm64` and `iosX64` targets to `test` module

### CODE REVIEW

**Comment by twyatt** [comment]
@cedrickcooke unit test is failing. It appears that the compiler changed anonymous class names.

https://github.com/JuulLabs/tuulbox/blob/0859e365c9bdaca44917a81f8efe9126b1299cd5/logging/src/jvmTest/kotlin/StackTraceTagGeneratorTests.kt#L16-L28

Printing out `supplier::class.java.name` shows: `com.juul.tuulbox.logging.StackTraceTagGeneratorTests$$Lambda$4/2136709118`

I should probably just was a static string for the `expected`?

**Comment by cedrickcooke** [comment]
This is a legit failure. If they've changed the format for the anonymous class names, then both the expected value and the implementation of `StackTraceTagGenerator` need to change. I can take a look at finding a new regex that works.

**Comment by twyatt** [comment]
> If they've changed the format for the anonymous class names, then both the expected value and the implementation of `StackTraceTagGenerator` need to change.

If a consumer of the library is using an older Kotlin version, will our regex still work? Or do we need to pick a regex based on the Kotlin compiler used by the library consumer?

**Comment by cedrickcooke** [comment]
I think it'll be: `(\$\$Lambda)?\$([0-9\/]+)$`. I am not 100% sure if you need to escape forward slashes in JVM's regex, if you don't it would be `(\$\$Lambda)?\$([0-9/]+)$`

> If a consumer of the library is using an older Kotlin version, will our regex still work?

The above regex is strictly more permissive, it'll match anything the old regex did.

**Comment by cedrickcooke** [comment]
Ah, and we'll also need to change the "Substring before". Probably just a `$` instead of `$1` should be fine in this case.

**Comment by twyatt** [comment]
New regex is failing on Tuulbox 4.1.0:

```
Expected :StackTraceTagGeneratorTests
Actual   :StackTraceTagGeneratorTests$tagStripsAnonymousClassNumber$supplier$1
```

**Review by cedrickcooke — APPROVED** [review]

**Review by QuantumRand — APPROVED** [review]

**Pull request merged**
